# Fedora base image
FROM fedora:latest

# Install build tools and dependencies
RUN dnf -y install \
    cmake \
    gcc \
    gcc-c++ \
    make \
    SDL2-devel \
    SDL2-static \
    git \
    python3 \
    python3-pip

WORKDIR /workspace

# Entrypoint for interactive shell
ENTRYPOINT ["/bin/bash"]
