# Fedora base image
FROM fedora:latest

# Install build tools and dependencies
RUN dnf -y install \
    cmake \
    gcc \
    gcc-c++ \
    make \
    SDL2-devel \
    SDL2-static \
    git \
    python3 \
    python3-pip \
    libXext-devel \
    libXcursor-devel \
    libXinerama-devel \
    libXi-devel \
    libXrandr-devel \
    libXrender-devel \
    libXfixes-devel \
    libXxf86vm-devel \
    libXdamage-devel \
    libXcomposite-devel \
    libXdmcp-devel \
    glew-devel

WORKDIR /workspace

# Entrypoint for interactive shell
ENTRYPOINT ["/bin/bash"]
